apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: waynerferreira13/gitopswf
  newTag: 26e41550b22d656d720996fc23119e605a4962f9
