apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: waynerferreira13/gitopswf
  newTag: 32c24621cd54a3908e697fda0e8d8cff08cfc1d8
